name: BranchBuild

on:
  push: 
    branches:
      - release*  # Matches any branch starting with 'release'
      - dev       # Matches the 'dev' branch exactly

jobs:
  build:
    #if: ${{ startsWith(github.ref_name, 'release') || github.ref_name == 'dev' }}
    runs-on: ubuntu-latest 
    steps:
      - name: Step 1
        run: echo "this is step 1 Build"  
  
  test:
    runs-on: ubuntu-latest
    name: Test Job
    needs: build
    steps: 
      - name: Step 1
        run: echo "this is step 1 Test" 
       