name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [staging, production]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
        
      - name: Use secret in script
        run: |
          echo "Using the secret in a script"
          echo "My secret is $MY_SECRET"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
