name: CI-Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Step 1
        run: echo "this is step 1 Build"  
      - name: Step 2
        run: echo "this is step 2  Build"
      - name: Step 3
        run: echo "this is step 3  Build"
      - name: Step 4
        run: echo "this is step 4  Build"
  test:
    runs-on: ubuntu-latest
    name: A job to say hello test
    steps: 
      - name: Step 1
        run: echo "this is step 1 Test" 
      - name: Step 2
        run: echo "this is step 2 Test"
      - name: Step 3
        run: echo "this is step 3 Test"
      - name: Step 4
        run: echo "this is step 4 Test"
    