name: CI-Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - name: Step 1
        run: echo "this is step 1 Build"  
      - name: Step 2
        run: echo "this is step 2 Build"
      - name: Step 3
        run: echo "this is step 3 Build"
      - name: Step 4
        run: echo "this is step 4 Build"

  test:
    runs-on: ubuntu-latest
    name: Test Job
    needs: build
    steps: 
      - name: Step 1
        run: echo "this is step 1 Test" 
      - name: Step 2
        run: echo "this is step 2 Test"
      - name: Step 3
        run: echo "this is step 3 Test"
      - name: Step 4
        run: echo "this is step 4 Test"

  scan:
    runs-on: ubuntu-latest
    name: Scan Code
    needs: build
    steps: 
      - name: Step 1
        run: echo "this is step 1 Scan" 

  promote:
    runs-on: ubuntu-latest
    name: Promote Job
    needs: 
      - test
      - scan
    steps: 
      - name: Step 1
        run: echo "this is step 1 Promote"

  deploy:
    runs-on: ubuntu-latest
    name: Deploy Job
    needs: promote
    environment: production
    steps: 
      - name: Step 1
        run: echo "this is step 1 Deploy"
