name: CI-Build

on:
  push
  

jobs:
  build:
    runs-on: ubuntu-latest
    - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # Choose a distribution (temurin is the new name for AdoptOpenJDK)

    name: Build Job
    steps:
      - name: Step 1
        run: java --version 
       