name: Update PR Status

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update-pr-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Update PR Status
        run: |
          # Set the GitHub API URL for updating the PR status
          api_url="https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}"
          
          # Create the JSON payload
          payload=$(cat <<-END
          {
            "state": "success",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "description": "The build succeeded!",
            "context": "ci/build"
          }
          END
          )
          
          # Send the POST request to update the status
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d "$payload" "$api_url"
