name: PR-Status
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - release* 

jobs:
  build:
    runs-on: ubuntu-latest 
    name: Build Job

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' 
      - name: Step 1
        run: java --version 
      - name: Update PR status to success
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const headers = { 'user-agent': 'request' };
            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha: context.sha,
              state: 'success',
              context: 'CI',
              description: 'Build and tests passed',
              target_url: context.payload.pull_request.html_url,
              headers
            });
      - name: Update PR status to failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const headers = { 'user-agent': 'request' };
            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha: context.sha,
              state: 'failure',
              context: 'CI',
              description: 'Build or tests failed',
              target_url: context.payload.pull_request.html_url,
              headers
            });