name: CI Workflow

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set environment variable
        id: set-env
        run: echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Use secret in script
        run: |
          echo "Using the secret in a script"
          echo "Selected environment is $ENVIRONMENT"
          echo "My secret is $MY_SECRET"
          echo "My repo secret is $REPO_SECRET"
        env:
          MY_SECRET: "${{ secrets['MY_SECRET_' + github.event.inputs.environment] }}"
          REPO_SECRET: "${{ secrets['REPO_SECRET_' + github.event.inputs.environment] }}"
