name: myfirst
on:
  push:
jobs:
  build:
    name: first stage
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2

      - name: build package
        run: |
          mkdir dist
          echo "Im a on build package"  > dist/abc.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            dist 

  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
        
      - name: check files
        run: |
          ls -la 


          
