name: PassingVariables

on: 
  push 

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
        
      - name: Set environment variable
        id: set-env
        run: echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV 

      - name: Use secret in script
        run: |
          echo "Using the secret in a script"
          echo "Selected environment is $ENVIRONMENT" 

  deploy:
    runs-on: ubuntu-latest 
    needs: build
    steps:   
      - name: Deploy application
        run: |
          echo "Using the secret in a script"
          echo "Selected environment is $ENVIRONMENT" 
    
 