name: Webhook Triggered

on:
  repository_dispatch:
    types: 
      - webhook

jobs:
  webhook-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "This workflow was triggered by a webhook call!"
